import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>React PWA Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="manifest" href="/manifest.webmanifest.json" />
      </Head>

      <h1 className={styles.title}>React PWA Boilerplate</h1>

      <p className={styles.description}></p>
    </div>
  );
}
